### ISSUE TITLE
extra-long incorrect prophage calls

### ISSUE THREAD

**Issue by k6logc** [mtisza1/Cenote-Taker3#6] opened 2024-04-02 23:35 UTC
Hi Mike, 

Thank you for Cenote-Taker3! We liked Cenote-Taker2 and are excited to explore your update. In our early runs we've noticed some examples of extra-long regions (>2,000,000 bases) being incorrectly called as prophages. In general our runs look reasonable and we haven't yet sorted out why this is happening in some cases. Do you have any insight into what might be going on?

**We have v3.3.0 and the updated databases, and are running as:**
cenotetaker3 -c $inDIR/$1 -r $modified_base -p T --lin_minimum_hallmark_genes 2 --cpu 6 --cenote-dbs $ct3DBpath

**Examples of genomes that yield wonky hits:**
https://www.homd.org/ftp/genomes/PROKKA/V10.1/fna/SEQF1065.1.fna
https://www.homd.org/ftp/genomes/PROKKA/V10.1/fna/SEQF9972.1.fna

Any feedback or guidance much appreciated, thank you!

-Kathryn (& looping in @AmrutaIdagunji who is working on this)

**Comment by mtisza1** [comment] 2024-04-03 19:51
Hi Kathryn,

Thanks for opening this issue. I just tested the SEQF1065.1.fna file, and I found the problem. `CT3` is behaving as expected, in this case, the sequence "SEQF1065.1|CP003503.1 HMT-643 Prevotella intermedia 17" has DTRs/Direct Terminal Repeats. Therefore, `CT3` treats it as circular and therefore does not prune. See log message "assess_virus_genes1.py: No non-DTR virus contigs >= 10,000 nt. So pruning will not happen" when running this file.

Would it be useful to you if I added a flag to force pruning on DTR sequences? I'm planning some small updates and I believe I can implement this.

Let me know,

Mike

**Comment by k6logc** [comment] 2024-04-03 22:43
Hi Mike,

Thank you very much for checking this out and for your quick diagnosis. Yes, it would be fantastic if you could add the option to force a prune on DTR seqs. In the case of SEQF1065.1 we expect to have two 30-40kb prophages predicted on that contig and it will be great to see if the force prune recovers them. Do you have a ballpark sense on timeline for your next planned update?

Many thanks!

Best,
Kathryn

**Comment by mtisza1** [comment] 2024-04-03 23:23
Kathryn,

I'm happy to help. I would anticipate the update to be live in about 1 week.

I know that this doesn't help from a pipeline perspective, but if you are just curious about the few cases you mentioned in your earlier post, you can remove the DTR sequence from the beginning or end of your contigs before feeding it to `CT3`. You can find these sequences in `CT3` output files, e.g. "final_genes_to_contigs_annotation_summary.tsv"

Mike

**Comment by k6logc** [comment] 2024-04-04 02:00
Hi Mike,

Great about the timing on the update! We are looking forward to reflecting those changes in our pipeline as well. And thank you for mentioning about trimming the DTRs for seeing what's going on in those cases, makes sense.

Thank you!

Best,
Kathryn

**Comment by mtisza1** [comment] 2024-04-12 17:42
Hi Kathryn,

I've put a new version `v3.3.1` on Bioconda. see [release](https://github.com/mtisza1/Cenote-Taker3/releases/tag/v3.3.1).

I've added the flag `--max_dtr_assess` (which defaults to 1,000,000). This allows you to set the length at which `CT3` stops looking for DTRs. This way, assemblies of complete circular bacterial chromosomes with prophage will get pruned instead of treated like circular/DTR viruses.

Please update to `v3.3.1`. This should do it:

`conda activate ct3_env`

`mamba install bioconda::cenote-taker3=3.3.1`

Let me know if this fixes your issue.

Mike

**Comment by k6logc** [comment] 2024-04-14 14:40
Hi Mike,
Fantastic, thank you!! Will report back.
Best,
Kathryn

**Comment by mtisza1** [comment] 2024-06-28 20:45
Kathryn, I'm going to close this issue with the assumption that this new function is working for you. Please reopen it if that's not the case. 

Best,

Mike

**Closed by mtisza1** 2024-06-28 20:45 UTC

**Comment by k6logc** [comment] 2025-10-06 01:09
Hi Mike, 

Thank you very much for adding in the `--max_dtr_assess` to help resolve the long calls issue. I'm finding that we are still seeing some really large calls slip through though (up to >5MB), I've dropped in some example GCA ids / fna links below. If you would be able to tell what's happening with these guys and how we can prevent this that would be really great. We're seeing it with both of following two configurations:

- v3.4.0 `cenotetaker3 -c {params.fnaDIR} -r {params.strain} -p T --lin_minimum_hallmark_genes 2 --cpu $cenoteCores --hhsuite_tool hhblits`
- v3.4.1 `cenotetaker3 -c {params.fnaDIR} -r {params.strain} -p T --lin_minimum_hallmark_genes 2 --wrap F --max_dtr_assess 0 --cpu $cenoteCores --hhsuite_tool hhblits`

Thank you!

Best,
Kathryn
```
GCA_018292145.1	https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/018/292/145/GCA_018292145.1_ASM1829214v1/GCA_018292145.1_ASM1829214v1_genomic.fna.gz
GCA_009648915.1	https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/009/648/915/GCA_009648915.1_ASM964891v1/GCA_009648915.1_ASM964891v1_genomic.fna.gz
GCA_007197715.1	https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/007/197/715/GCA_007197715.1_ASM719771v1/GCA_007197715.1_ASM719771v1_genomic.fna.gz
GCA_008586825.1	https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/008/586/825/GCA_008586825.1_ASM858682v1/GCA_008586825.1_ASM858682v1_genomic.fna.gz
GCA_000251605.2	https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/251/605/GCA_000251605.2_ASM25160v2/GCA_000251605.2_ASM25160v2_genomic.fna.gz
GCA_018916935.1	https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/018/916/935/GCA_018916935.1_ASM1891693v1/GCA_018916935.1_ASM1891693v1_genomic.fna.gz
GCA_000232645.2	https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/232/645/GCA_000232645.2_ASM23264v2/GCA_000232645.2_ASM23264v2_genomic.fna.gz
GCA_005862145.1	https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/005/862/145/GCA_005862145.1_ASM586214v1/GCA_005862145.1_ASM586214v1_genomic.fna.gz
```

**Comment by mtisza1** [comment] 2025-10-07 21:25
Hi Kathryn,

Thank you for bringing this issue to my attention. It turns out to be an interesting bug. 

I checked the first four genomes you listed. They each have no predicted genes in the first 5 kb, per pyrodigal prediction. This could be due to the wrap point occurring in the middle of a very long gene or in a long intergenic region.

In `CT3`'s prophage pruning module, the lack of genes in the first 5 kb caused the unexpected behavior of calling the entire chromosome as a continuous prophage-like region. I fixed the logic and released a new version `v3.4.2`. The new version should be available in the day or two.

I will close this issue. I'm curious: how common was this whole-chromosome prophage bug?

https://github.com/mtisza1/Cenote-Taker3/releases/tag/v3.4.2

Best,

Mike

**Comment by k6logc** [comment] 2025-10-07 22:02
Hi Mike, 

Wonderful!! Thank you so much for figuring it out and fixing it so super quickly, really appreciate it. 

We didn't systematically evaluate the frequency of the whole-chromosome bug but the easy ones to see were the super long examples and we had ~10 examples of >500kb predictions in a set of ~8k genomes. 

Best,
Kathryn

**Comment by mtisza1** [comment] 2025-10-07 22:13
Thanks so much for that info. If it was as rare as you estimate, and the four genomes I tested had the same problem and solution, then I imagine that the lack of genes in the first 5 kb is the main problem.

**Comment by k6logc** [comment] 2025-10-08 01:06
That makes sense, I will run with v3.4.2 and let you know if any more oddballs crop up. Many thanks!
